### ISSUE TITLE
Cyrillic letters for regexps

### ISSUE THREAD

**Issue by wwall** [rufoa/cljcc#2]
Many thanks for publish in clojars for tis package. 
I have next question - 
How i could write regexp with Cyrillic letter for case-insensitive?

f.e.

(def tokens
  #{
    { :name :lxmVAR-en  :pattern #"(?i)var" }
    { :name :lxmVAR-ru  :pattern #"перем" }
    { :name :ws   :pattern #"\s+" }})

(defn tst [text](let [lex %28make-lexer tokens%29]
    %28into[] %28lex text%29%29))

(tst "var") or (tst "VAr") is ok for this regexp
(tst "перем") also is ok, 
but, if i change declaration to 
(def tokens
  #{
    { :name :lxmVAR-en  :pattern #"(?i)var" }
    { :name :lxmVAR-ru  :pattern #"(?i)перем" }
    { :name :ws   :pattern #"\s+" }})

then 
 (tst "ПЕРЕм") is error, and  (tst "перем") so  is error

How i can fix it? How use national alphabet in regexp? Can you write any example?

**Comment by rufoa** [comment]
I'm not sure - I haven't tried it with Cyrillic characters.

I will investigate this problem and reply soon.

**Comment by rufoa** [comment]
cljcc only supports a limited subset of regexes. Unfortunately this does not include the `(?i)` modifier (either in Latin or Cyrillic).

The easiest solution is this:

``` clojure
(def tokens #{{:name :lxmVAR-ru :pattern #"[пП][еЕ][рР][еЕ][мМ]"}})
(let [lex (make-lexer tokens)]
   (lex "ПерЕМ"))
```

=>

``` clojure
({:consumed "ПерЕМ",
  :position #cljcc.lexer.Position{:char 1, :line 1},
  :token-name :lxmVAR-ru}
 {:position #cljcc.lexer.Position{:char 6, :line 1}, :token-name :$})
```

**Comment by rufoa** [comment]
New feature in [v0.1.2](https://clojars.org/cljcc/versions/0.1.2):

String tokens can use `:ci true` to turn on case-insensitive matching.

``` clojure
(def tokens #{{:name :lxmVAR-ru :pattern "перем" :ci true}})
(let [lex (make-lexer tokens)]
   (lex "ПерЕМ"))
```

=>

``` clojure
({:consumed "ПерЕМ",
  :position #cljcc.lexer.Position{:char 1, :line 1},
  :token-name :lxmVAR-ru}
 {:position #cljcc.lexer.Position{:char 6, :line 1}, :token-name :$})
```

Hope this is useful!

**Comment by wwall** [comment]
Hello. I install new version and write this code

(ns loxy.core
  (:require [cljcc :refer [make-lexer]]))

(def tokens
  #{
    ;;; арифметические операции
    { :name :lxmPLUS    :pattern "+" }
    { :name :lxmMINUS   :pattern "-" }
    { :name :lxmDIV     :pattern "/" }
    { :name :lxmMUL     :pattern "*" }
    { :name :lxmMOD     :pattern "%" }
    ;;; пунктуация 
    { :name :lxmOPEN    :pattern "(" }
    { :name :lxmCLOSE   :pattern ")" }
    { :name :lxmBOPEN   :pattern "[" }
    { :name :lxmBCLOSE  :pattern "]" }
    { :name :lxmCOMMA   :pattern "," }
    { :name :lxmDOT     :pattern "." }
    { :name :lxmEND     :pattern ";" }

```
;;; операции
{ :name :lxmEQU     :pattern "=" }
{ :name :lxmNOTEQU  :pattern "<>" }
{ :name :lxmLT      :pattern "<" }
{ :name :lxmLTEQU   :pattern "<=" }
{ :name :lxmGT      :pattern ">" }
{ :name :lxmGTEQU   :pattern ">=" }

;;; ключевые слова
{ :name :lxmVAR-en  :pattern "var" :ci true }
{ :name :lxmVAR-ru  :pattern "перем" :ci true }

;;; константные литералы

{ :name :number     :pattern #"\d+(\.\d+)?"
                    :valuation-fn #(Integer/parseInt (second %) )}    
{ :name :tkn :pattern #"[a-zA-zа-яА-Я]+" :priority -1}
{ :ignore true :pattern #"\s+" }})
```

(defn tst [str](let [lex %28make-lexer tokens%29]
    %28map %28fn [x] [%28:token-name x%29 %28:consumed x%29]%29 %28lex str%29%29))

for run 
loxy.core> (tst "перем ПЕрем")
output is ([:lxmVAR-ru "перем"] [:tkn "ПЕрем"] [:$ nil])
loxy.core> (tst "var Var")
([:lxmVAR-en "var"] [:tkn "Var"] [:$ nil])

what i have done wrong?

but code 
(def tokens #{{:name :lxmVAR-ru :pattern #"[пП][еЕ][рР][еЕ][мМ]"}})
(let [lex (make-lexer tokens)](lex))

works fine

**Comment by wwall** [comment]
if you need to see full code - my project is here https://github.com/wwall/loxy

**Comment by rufoa** [comment]
The code you pasted above works for me:

``` clojure
=> (tst "перем ПЕрем")
([:lxmVAR-ru "перем"] [:lxmVAR-ru "ПЕрем"] [:$ nil])

=> (tst "var Var")
([:lxmVAR-en "var"] [:lxmVAR-en "Var"] [:$ nil])
```

Please double check that `:tkn` has `:priority -1`?

**Comment by rufoa** [comment]
Unrelated problem:

``` clojure
{ :name :number     :pattern #"\d+(\.\d+)?"
                    :valuation-fn #(Integer/parseInt (second %) )}
```

This is incorrect - you probably want e.g.:

``` clojure
{ :name :number     :pattern #"\d+(\.\d+)?"
                    :valuation-fn #(Float/parseFloat (first %) )}
```

**Comment by wwall** [comment]
Many thanks. All works. You can close task.
You library is very good and usefull. 
I have only one wishes - can you add  lazy for lexer? sometime need get any small number tokens from stream, and i think what 

(take 2 ((make-lazy-lexer tokens) "1+2+3"))) is good extension for you library.

**Comment by rufoa** [comment]
Please upgrade to 0.1.3 - important bug and performance fixes

---

It should already be lazy I think! :smile:

``` clojure
loxy.core=> (time (let [lazy ((make-lexer tokens) (slurp "data/tst.txt"))] (doall (take 2 lazy))))
"Elapsed time: 33.510516 msecs"
({:consumed "#Если",
  :position #cljcc.lexer.Position{:char 1, :line 1},
  :token-name :#IF-ru}
 {:consumed " ",
  :position #cljcc.lexer.Position{:char 6, :line 1},
  :token-name :ws})
```

**Comment by wwall** [comment]
You're a wizard. Very pleased that you so quickly react to my wishes. Thank you so much for your help

**Comment by rufoa** [comment]
You're welcome!
