### ISSUE TITLE
big text input

### ISSUE THREAD

**Issue by wwall** [rufoa/cljcc#3]
i have code 
https://gist.github.com/wwall/ca6b75128567dfc8dd23

And when i try tokenize big file ( 6 megabyte) i have error  Unhandled java.lang.StackOverflowError

how i can fix it?

**Comment by rufoa** [comment]
That's strange. I will investigate the problem

**Comment by rufoa** [comment]
Could you upload the 6MB file please?
Or post a stacktrace?

Many thanks

**Comment by wwall** [comment]
[DataProcessor.ДокументооборотСКонтролирующимиОрганами.ObjectModule.txt](https://github.com/rufoa/cljcc/files/109380/DataProcessor.ObjectModule.txt)
File for test.

**Comment by rufoa** [comment]
This is a problem with Java's RegExp [(see reference)](https://stackoverflow.com/a/7510006)

```
java.lang.StackOverflowError: 

loxy.lexer=> (clojure.repl/pst)

        java.util.regex.Pattern$Loop.match  Pattern.java: 4785
   java.util.regex.Pattern$GroupHead.match  Pattern.java: 4658
      java.util.regex.Pattern$Branch.match  Pattern.java: 4604
java.util.regex.Pattern$CharProperty.match  Pattern.java: 3777
  java.util.regex.Pattern$BranchConn.match  Pattern.java: 4568
   java.util.regex.Pattern$GroupTail.match  Pattern.java: 4717
        java.util.regex.Pattern$Loop.match  Pattern.java: 4785
   java.util.regex.Pattern$GroupHead.match  Pattern.java: 4658
      java.util.regex.Pattern$Branch.match  Pattern.java: 4604
.......
```

It is triggered by the `|` in the `:tknSTRING` pattern and the large string on line 1424 in the file.

The easiest solution is to change your regex pattern to remove the `|`

``` clojure
{ :name :tknSTRING
  :pattern #"\"(([^\"]*(\"\")*)*)\"" }
```

Hope this helps

**Comment by rufoa** [comment]
To change the `""` into `"` you can use `:valuation-fn`:

``` clojure
{ :name :tknSTRING
  :pattern #"\"(([^\"]*(\"\")*)*)\"" }
  :valuation-fn #(clojure.string/replace (second %) "\"\"" "\"") }
```

So:

``` clojure
loxy.core=> ((make-lexer raw-tokens) "\"foo\"\"bar\"")

({:consumed "\"foo\"\"bar\"",
  :position #cljcc.lexer.Position{:char 1, :line 1},
  :token-name :tknSTRING,
  :value "foo\"bar"}
...
```

**Comment by rufoa** [comment]
Closing this issue because it seems to be resolved. Please re-open if you have any problems
