### ISSUE TITLE
error in regexp with Cyrrylic sign

### ISSUE THREAD

**Issue by wwall** [rufoa/cljcc#4]
Hello
i write simple lexer
(def tt
  #{
    { :name :lxmOPEN   :pattern "(" }
    { :name :lxmBOPEN   :pattern "[" }
    { :name :tknID         :pattern #"[a-zA-zа-яА-Я_][a-zA-zа-яА-Я_0-9]*" :priority -1 }})
when i try 

> ((make-lexer tt) "[")

i get answer 
({:consumed "[", :position #cljcc.lexer.Position{:line 1, :char 1}, :token-name :lxmBOPEN} {:position #cljcc.lexer.Position{:line 1, :char 2}, :token-name :$})
it's right
but when i try 

> ((make-lexer tt) "x[x")

i have answer 
({:consumed "x[x", :position #cljcc.lexer.Position{:line 1, :char 1}, :token-name :tknID} {:position #cljcc.lexer.Position{:line 1, :char 4}, :token-name :$})
which not correct
but when i write

> ((make-lexer tt) "x(x")

({:consumed "x", :position #cljcc.lexer.Position{:line 1, :char 1}, :token-name :tknID} {:consumed "(", :position #cljcc.lexer.Position{:line 1, :char 2}, :token-name :lxmOPEN} {:consumed "x", :position #cljcc.lexer.Position{:line 1, :char 3}, :token-name :tknID} {:position #cljcc.lexer.Position{:line 1, :char 4}, :token-name :$})
i have correct answer
where is  error? Help me, please

**Comment by rufoa** [comment]
There is a mistake in your regex `#"[a-zA-zа-яА-Я`...
It should be this instead: `#"[a-zA-Zа-яА-Я`...

(Note capital letter Z, not small letter z)

The problem occurs because your range `A-z` (ASCII 65-122) contains `[` (ASCII 91)

Hope this helps!

**Comment by wwall** [comment]
Thank you so much for helping find a bug.
